services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"   # Expone el puerto 80 del contenedor al puerto 5000 de la máquina local
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - CONNECTIONSTRINGS__DEFAULTCONNECTION=Host=db;Port=5432;Database=MarcasAuto;Username=postgres;Password=password
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: MarcasAuto
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"  # Expone el puerto 5432 del contenedor al puerto 5432 de la máquina local
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
