// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Persistence;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(AutosDbContext))]
    [Migration("20241219012123_first")]
    partial class first
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MarcasAUtosAPI.Domain.MarcaAuto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Abreviatura")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Id");

                    b.HasKey("Id");

                    b.ToTable("MarcasAuto", t =>
                        {
                            t.Property("Id")
                                .HasColumnName("Id1");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abreviatura = "Hyu",
                            Descripcion = "Hyundai Motor Company fabricante Surcoreano",
                            FechaCreacion = new DateTime(2024, 12, 19, 1, 21, 22, 864, DateTimeKind.Utc).AddTicks(2067),
                            Nombre = "Hyundai"
                        },
                        new
                        {
                            Id = 2,
                            Abreviatura = "Nis",
                            Descripcion = "Nissan fabricante Japones",
                            FechaCreacion = new DateTime(2024, 12, 19, 1, 21, 22, 864, DateTimeKind.Utc).AddTicks(2637),
                            Nombre = "Nissan"
                        },
                        new
                        {
                            Id = 3,
                            Abreviatura = "Toy",
                            Descripcion = "Marca Toyota se fabrica en muchos lugares del mundo",
                            FechaCreacion = new DateTime(2024, 12, 19, 1, 21, 22, 864, DateTimeKind.Utc).AddTicks(2639),
                            Nombre = "Toyota"
                        },
                        new
                        {
                            Id = 4,
                            Abreviatura = "Kia",
                            Descripcion = "Kia Motors  fabricante Surcoreano",
                            FechaCreacion = new DateTime(2024, 12, 19, 1, 21, 22, 864, DateTimeKind.Utc).AddTicks(2640),
                            Nombre = "KIA"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
